variables:
  DOCKER_HOST: tcp://docker:2375
  #DOCKER_HOST: tcp://localhost:2375
  #DOCKER_DRIVER: overlay2
  #DOCKER_TLS_VERIFY: 1
 # DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
  DOCKER_TLS_CERTDIR: ""
  # `showDateTime` will show the passed time in milliseconds. You need to specify `--batch-mode` to make this work.
  MAVEN_OPTS: >-
    -Dhttps.protocols=TLSv1.2
    -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
    -Dorg.slf4j.simpleLogger.showDateTime=true
    -Djava.awt.headless=true

  # As of Maven 3.3.0 instead of this you MAY define these options in `.mvn/maven.config` so the same config is used
  # when running from the command line.
  # As of Maven 3.6.1, the use of `--no-tranfer-progress` (or `-ntp`) suppresses download and upload messages. The use
  # of the `Slf4jMavenTransferListener` is no longer necessary.
  # `installAtEnd` and `deployAtEnd` are only effective with recent version of the corresponding plugins.
  MAVEN_CLI_OPTS: >-
    --batch-mode
    --errors
    --fail-at-end
    

# This template uses the latest Maven 3 release, e.g., 3.8.6, and OpenJDK 8 (LTS)
# for verifying and deploying images
# Maven 3.8.x REQUIRES HTTPS repositories.
# See https://maven.apache.org/docs/3.8.1/release-notes.html#how-to-fix-when-i-get-a-http-repository-blocked for more.
image: maven:3.6.1-jdk-11

# Cache downloaded dependencies and plugins between builds.
# To keep cache across branches add 'key: "$CI_JOB_NAME"'
# Be aware that `mvn deploy` will install the built jar into this repository. If you notice your cache size
# increasing, consider adding `-Dmaven.install.skip=true` to `MAVEN_OPTS` or in `.mvn/maven.config`
cache:
  key: mavenrepo
  paths:
    - ./.m2/repository

stages:
    - build 
    - test
    - checkstyle
    - container
    - k8s
build-stage:
    stage: build
    script:
        - 'mvn $MAVEN_CLI_OPTS package'
    artifacts:
      when: always
      paths:
        - /builds/gopal1409/spring-chat-app
test-stage:
    stage: test
    script:
        - 'mvn $MAVEN_CLI_OPTS test'
    artifacts:
      paths:
        - target/surefire-reports/*.xml
      untracked: false
      when: on_success
      expire_in: 30 days
checkstyle-stage:
    stage: checkstyle
    script:
        - 'mvn $MAVEN_CLI_OPTS checkstyle:checkstyle'
build container image:
  stage: container
  when: manual
  image: docker:24.0.5
  services:
    - docker:24.0.5
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  before_script:
    - docker info
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG

